### ISSUE TITLE
Pingdom script doesn't detect transaction errors anymore?

### ISSUE THREAD

**Issue by walro** [twingly/marvin#11]
We keep seeing things like "Pingdom: BRM discover (production) is SUCCESSFUL" in yellow. We don't see anything red or green these days.

**Comment by walro** [comment]
We got a "Pingdom: BRM discover (production) is FAILING" just now, still in yellow though.

**Comment by walro** [comment]
Today we got a `Pingdom: Twingly.com search login is SUCCESSFUL` even thought the check was failing when looking at the actual web page.

**Comment by jage** [comment]
Pingdom has finally added some documentation to the webhook system: https://www.pingdom.com/resources/webhooks

**Comment by dentarg** [comment]
Seems to be working

>Marvin Pingdom notification	
>10:08
>Pingdom: https://app.twingly.com/login is failing

>Marvin Pingdom notification	
>10:10
>Pingdom: https://app.twingly.com/login is successful

Although we don't get pretty colors (red/green), both of these were yellow in chat.
