### ISSUE TITLE
Use Pingdom's new webhook format

### ISSUE THREAD

**Issue by walro** [twingly/marvin#17]
Pingdom has deprecated the old format.

From [Trello](https://trello.com/c/ZYXD0VMA/829-b%C3%B6rja-anv%C3%A4nda-pingdoms-nya-webhook-format) and [Trello comment](https://trello.com/c/b4pHYo7p/2144-sprint45-extra-support-migrera-till-pingdoms-nya-notis-system#comment-59a7fd234b9ae7cc679d53db).

**Comment by dentarg** [comment]
Detta talar ju rätt mycket för att börja använda en chatt-tjänst som kommer med en native integration mot Pingdom.

**Comment by jage** [comment]
Yes, getting the notifications from Pingdom is very important.
